# Generated by Django 5.1.1 on 2025-01-09 17:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0002_alter_jobseekerapimodel_resume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobSeekerApiModel',
            new_name='JobSeeker',
        ),
    ]
