# Generated by Django 5.1.1 on 2025-01-15 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0003_rename_jobseekerapimodel_jobseeker'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='job_seeker/profile_images/'),
        ),
    ]
