# Generated by Django 5.1.1 on 2025-01-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0004_jobseeker_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
