# Generated by Django 5.1.1 on 2025-01-09 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryApiModel',
            new_name='Category',
        ),
    ]
