# Generated by Django 5.1.1 on 2025-01-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Full_Time', 'Full Time'), ('Part_time', 'Part Time'), ('internship', 'Internship')], default='Part_time', max_length=20, null=True),
        ),
    ]
